<div class="tradingview-widget-container mb-4">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-stock-heatmap.js" async>
        {
            "exchanges": [
            "ADX",
            "AMEX",
            "ASX",
            "BCBA",
            "BCS",
            "BER",
            "BET",
            "BIST",
            "BIVA",
            "BVCV",
            "BME",
            "BMFBOVESPA",
            "BSE",
            "BVC",
            "BX",
            "CSECY",
            "DUS",
            "EGX",
            "EURONEXT",
            "FWB",
            "GPW",
            "HAM",
            "HNX",
            "IDX",
            "JSE",
            "KRX",
            "KSE",
            "MIL",
            "MUN",
            "NASDAQ",
            "NASDAQDUBAI",
            "NEO",
            "NEWCONNECT",
            "NYSE",
            "OMXCOP",
            "OMXHEX",
            "OMXICE",
            "OMXRSE",
            "OMXSTO",
            "OMXTSE",
            "OMXVSE",
            "OTC",
            "SIX",
            "SSE",
            "TASE",
            "TPEX",
            "TSX",
            "TSXV",
            "UPCOM",
            "XETR"
        ],
            "dataSource": "SPX500",
            "grouping": "sector",
            "blockSize": "market_cap_basic",
            "blockColor": "change",
            "locale": "en",
            "symbolUrl": "",
            "colorTheme": "dark",
            "hasTopBar": false,
            "isDataSetEnabled": false,
            "isZoomEnabled": true,
            "hasSymbolTooltip": true,
            "isMonoSize": false,
            "width": "100%",
            "height": "800"
        }
    </script>
</div>
